### ISSUE TITLE
希望添加一个获得 $this->client 的公共方法

### ISSUE THREAD

**Issue by gclove** [iiDestiny/flysystem-oss#40]
OSS 官方的 sdk 还有 音视频处理等的其它 api, 

如果不获取到 `$client`, 没办法调用这些函数  @iiDestiny

**Comment by iiDestiny** [comment]
今天安排

**Comment by iiDestiny** [comment]
已完成，请更新 2.0 版本
2.0 版本发行说明：https://github.com/iiDestiny/flysystem-oss/releases/tag/2.0
