### ISSUE TITLE
阿里云官网给的PHP的OSS直传签名的时间算法是错的

### ISSUE THREAD

**Issue by ihipop** [iiDestiny/flysystem-oss#51]
https://github.com/iiDestiny/flysystem-oss/blob/fd689ddc00e93c998c376cc1f66a89d048eae3fb/src/Traits/SignatureTrait.php#L27-L36

比实际时间晚了8个小时，他生成0时区的算法就是把当前时间表示时区的部分裁剪掉然后强制改成0时区，所以真正的ticket过期时间是8小时以后

具体分析： https://blog.ihipop.info/2020/08/5260.html

**Comment by ihipop** [comment]
阿里云官方已经承认错误 https://connect.console.aliyun.com/connect/detail/162632

**Comment by iiDestiny** [comment]
亲，可以提交一个 pr 吗？

**Comment by ihipop** [comment]
> 亲，可以提交一个 pr 吗？

稍后
