### ISSUE TITLE
namespace Overtrue\Flysystem\Qiniu

### ISSUE THREAD

**Issue by rookie0** [iiDestiny/flysystem-oss#9]
https://github.com/iiDestiny/flysystem-oss/blob/master/tests/OssAdapterTest.php#L12
https://github.com/iiDestiny/flysystem-oss/blob/master/tests/helpers.php#L12

**Comment by iiDestiny** [comment]
哈哈。test 模仿的超哥的。粗心了

**Comment by iiDestiny** [comment]
已调整
